const GET_USERS = 'GET_USERS';
const GET_USERS_BY_ID = 'GET_USERS_BY_ID';
const POST_USER = 'POST_USER';
const DELETE_USER = 'DELETE_USER';
const UPDATE_USER = 'UPDATE_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const AUTH_USER = 'AUTH_USER';
const REFRESH_TOKEN = 'REFRESH_TOKEN';
const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
const SET_PASSWORD = 'SET_PASSWORD';

export {
    GET_USERS,
    GET_USERS_BY_ID,
    POST_USER,
    DELETE_USER,
    UPDATE_USER,
    LOGOUT_USER,
    AUTH_USER,
    REFRESH_TOKEN,
    FORGOT_PASSWORD,
    SET_PASSWORD
}